when@dev:
    survos_command:
        prefix: /commands
        type: attribute
        resource:
            path: '@SurvosCommandBundle/src/Controller/'
            namespace: Survos\CommandBundle\Controller
